# Generated by Django 3.1.1 on 2022-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20220920_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
